FROM --platform=linux/amd64 ubuntu:20.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y automake pkg-config libtool build-essential bison flex gettext autopoint texinfo

ADD . /repo
WORKDIR /repo
RUN ./autogen.sh
RUN ./configure
RUN make -j8
